# Generated by Django 4.1.6 on 2023-04-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projecte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('grau', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('grau', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
